amz-tools/amazon-sp-api

README.md, lib/credentials.js
In our production environment, we use Elastic Beanstalk. When we tried adding the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, it caused our aws-sdk to start using that key instead of authenticating with however Elastic Beanstalk does. Since Elastic Beanstalk does not set these variables and setting up a credentials file is not ideal for us, we'd like to see an alternative.
This PR adds alternate variable names for the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for those running in environments where this is not easy to set. I have tested this locally by running all the tests using the environment variables in .env.test as well as setting up a file using credentials_path.
=> Tweak: Add alternate variables for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

lib/request.js
When testing this in local didn't any problem but on dev-server start throwing "URL not defined", some versions of NodeJS doesn't come with the same URL integration. 
> https://nodejs.org/api/url.html#url_url 
Declaring it fixes de issue.
=> FIX: URL not defined in certain NodeJS versions

lib/Signer.js
Add extra optional parameter to contructor of Signer, false by default. 
When true it adds 'sandbox.' to the endpoint.
=> Add Sandbox

lib/SellingPartner.js
Adding sandbox just enableing a internal variable _sandbox which is set by the config object passed by the constructor. 
This Variable is also passed when signing the request (so the url matches the requested one)
Also catching error when sandbox mode is on and error.code is 'InternalFailure' this means sandbox parameters are not correct.
=> Add sandbox mode

lib/SellingPartner.js
One report didn't work for some reason, returning `quote_error` from csv conversion module. So i looked into report and found out one field name was starting with `"`, but wasnt ending with it, causing error. 
PR is an attempt at fixing it by turning off quote detection. Quotes in csv are used in cases when delimiter is used in field, for example if delimiter was `,` and you wanted to have comma in some field. I have tested failing report afterwards and it worked. I have manually checked multiple other reports with this fix and they all worked correctly, however that may not be the case for every report for every user.
=> Turn off quote detection in report csv to json conversion

lib/typings/index.d.ts
Good morning,
A few months ago I told you in an issue (https://github.com/amz-tools/amazon-sp-api/issues/59), if there were typings for upload functions.
I have created a basic one for feed upload, and it is tested under the feed API version 2021-06-30.
Regards.
=> added upload typings for feeds

lib/typings/baseTypes.ts
I was interested in TypeScript support for use_sandbox to be able to test sandbox mode in my typescript project  
so I added this type to the Options type of the constructor config
=> added use_sandbox property to Options Type in : baseTypes.ts

README.md, lib/SellingPartner.js, lib/Signer.js, lib/typings/baseTypes.ts
This change allows to specify custom user-agent headers for api calls.
Since user-agent header is not mandatory, default value for "user-agent" is `undefined`, it means user-agent header won't be included to requests.
=> Specifying custom user-agent headers for api calls

README.md, lib/SellingPartner.js, lib/typings/baseTypes.ts
Adding an option `console_warn_on_request_retry` for console warnings every time the client retries a request when throttled.
There was no easy way of seeing when the library is retrying requests without going into the source code. While developing I ended up having a lot of loops in the background with requests not knowing about it.
=> Adding an option for console warnings on throttle retries

lib/typings/operations/finances.ts
Exporting all interfaces allows users to declare their own functions that use those interfaces.  For example:
```
import { FinancialEventGroup } from 'amazon-sp-api/lib/typings/operations/finances';
```
=> Export all finances interfaces (Typescript support)

lib/Signer.js, lib/utils.js
While running productPricing.getListingOffers:
```
const res = await sellingPartner.callAPI({
operation: "productPricing.getListingOffers",
path: {
SellerSKU: "Merimieskirja+kynä",
},
query: {
MarketplaceId: "ATVPDKIKX0DER",
ItemCondition: "New",
},
});
```
The server responded with the following error:
```
error: Error: The request signature we calculated does not match the signature you provided. 
Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
The Canonical String for this request should have been
'GET/products/pricing/v0/listings/Merimieskirja%2Bkyn%25C3%25A4/offersItemCondition=New&MarketplaceId=ATVPDKIKX0DERhost:sellingpartnerapi-na.amazon.comuser-agent:amazon-sp-api/0.6.6 (Language=Node.js/v12.19.1; Platform=Linux/5.4.0-1057-aws …
```
=> double encoding fix for AWS Signature v4

README.md, lib/SellingPartner.js, lib/typings/IReqOptions.ts
... to address issue #101 
Example usage:
```
let res: GetOrderItemsResponse = await sellingPartner.callAPI({
operation: "orders.getOrderItems",
path: {
orderId: order.AmazonOrderId,
},
options: {
restore_rate: 5,
},
});
```
Debug output:
=> add restore_rate param to callAPI options

lib/typings/operations/orders.ts
The unused typescript intefaces 'OrderItemsBuyerInfoList' and 'OrderItemsList' in `lib/typings/operations/orders.ts` break our git pipeline. I commented them out for now, until you need them.
=> comment out unused order types

lib/endpoints.js, lib/operations.js
Hello,
I'm currently building an application that require a single javascript file as an entrypoint.
Problem is, since [this change](https://github.com/amz-tools/amazon-sp-api/commit/0bb9c6aed3957c6fd4f0ae3502c8462f13fa6e13), this is not possible anymore as the require process is dynamic.
As a result I get this error at runtime:
```
Error: ENOENT: no such file or directory, scandir '/workspace/connectors/amazon/build/cli/resources'
at readdirSync (node:fs:1392:3)
at null.../../node_modules/amazon-sp-api/lib/endpoints.js (/workspace/node_modules/amazon-sp-api/lib/endpoints.js:8:5)
at __require (/workspace/connectors/amazon/build/cli/index.js:25:50)
at null.../../node_modules/amazon-sp-api/lib/SellingPartner.js (/workspace/node_modules/amazon-sp-api/lib/SellingPartner.js:6:19)
at __require …
```
=> Make amazon-sp-api compatible with bundler again

lib/resources/catalogItems.js, lib/resources/versions/catalog_items/catalogItems_2022-04-01.js, test/specs/operations/catalogItems.spec.js
[New version of Catalog Items API](https://github.com/amzn/selling-partner-api-docs/discussions/2289)
This is the latest document  [URL](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#getcatalogitem)
=> Added catalogItems endpoint 2022-04-01 version

README.md, lib/Credentials.js, lib/Signer.js, package-lock.json
When running this library inside a Lambda function on AWS, this error occurs on  [refreshRoleCredentials()](https://github.com/amz-tools/amazon-sp-api/blob/main/lib/SellingPartner.js#L465):
```
{
"errorType": "Error",
"errorMessage": "The security token included in the request is invalid.",
"code": "InvalidClientTokenId",
"message": "The security token included in the request is invalid.",
"type": "error",
"stack": [
"Error: The security token included in the request is invalid.",
"    at SellingPartner.refreshRoleCredentials (/node_modules/amazon-sp-api/lib/SellingPartner.js:485:13)",
"    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
"    at SellingPartner._validateAccessTokenAndRoleCredentials (/node_modules/amazon-sp-api/lib/SellingPartner.js:255:9)",
"    at …
```
=> Fix assume role invalid client token

lib/Signer.js, lib/resources/versions/product_pricing/productPricing_v0.js
Regarding [issue #134](https://github.com/amz-tools/amazon-sp-api/issues/134)
It takes Amazon pretty long to reply. Let's have an update so meanwhile everything works properly.
I added a parameter `to_encode_query_twice` that you can include for any query you notice the same problem with double encoding. When Amazon fixes it, we can just remove the parameter from a specific endpoint that got fixed.
=> Add encode query twice option fix #134

lib/typings/operations/reports.ts
This PR is to update the interface CreateReportResponse to reflect that change in the function as it now unwraps the payload object by default.
=> Fix CreateReportResponse TypeScript Interface

README.md, lib/Signer.js, lib/request.js
Allows request to be aborted if it takes a lot longer than expected due to network errors.
Enabled by setting `options.request_timeout` and / or `options.deadline_timeout`; if these options are not set, the original behaviour (no timeout) is preserved. Sample code and description of options added to README.
resolves #147
=> Added response timeout and deadline timeout option support

README.md, lib/SellingPartner.js, lib/typings/index.d.ts
This seems to fix the #141  (also types are working after this change)
If its ok, the docs need to be fixed and normalized for the new export name
=> fix(named-exports): instead of `export default`

lib/request.js
This is related to #148 comment, about a timeoutManager object to separate responsibilities.
And also related to the merge of stream download (still I have to plan it)
The code is longer, but it should not be a regression.
I also added a fix for an edge case that probably would never happen, it is on 'error' event for req, that is rejected, but timeout may be still alive: no critical things would happen, because timeout just call .destroy() method on a dead req ...
Anyway it is there.
My plan is to split in another file, then use it in stream mode download ( #56 )
So @colin-brown please, I would like to hear some comment/review, thank you
=> a timeoutManager object

lib/typings/index.d.ts
Currently if I do:
```ts
sellingPartner.callAPI({
body: {
// body
},
operation: 'createReport'
});
```
There is no type inference. Fixed this issue
=> Add support for createReport types

lib/SellingPartner.js
Fixes the the bug in condition that checks for errors in callAPI method response, that lead to treating empty errors array as having an error.
=> Fixes empty errors array handling in call api method

lib/SellingPartner.js
should solve the 204 statusCode parsing bug #259 
We can also add a new guard to match a 204 response && method !== 'DELETE' and return `null`
This should be closer to amazon response
```js
if (res.statusCode === 204 && req_params.method === "DELETE") {
return { success: true };
}
if (res.statusCode === 204 && req_params.method !== "DELETE") {
return null;
}
```
=> 204 statusCode parsing bug

README.md, lib/Request.js, lib/SellingPartner.js
Currently the code used Node's inbuilt https agent which means you can't pass any proxy information if you are behind a firewall. This change allows the user to pass their own proxy agent using `hpagent` package like this:
```javascript
const { HttpsProxyAgent } = require('hpagent');
const agent = new HttpsProxyAgent({ proxy: 'http://x.x.x.x:zzzz' });
const spClient = new SellingPartner({
region: "eu",
options: {
httpsProxyAgent: agent
}
});
```
=> Added an option to use a custom proxy agent

lib/SellingPartner.js, lib/typings/baseTypes.ts, lib/typings/index.d.ts
@amz-tools You seem to document this functionality in https://github.com/amz-tools/amazon-sp-api/blob/a67512441db3e12473b02be7d4944c67a182b90f/README.md?plain=1#L525 but it doesnt seem reflected in code
=> fix: refreshAccessToken typings

lib/resources/versions/data_kiosk/dataKiosk_2023-11-15.js
This pull request includes a change to the `lib/resources/versions/data_kiosk/dataKiosk_2023-11-15.js` file to update the API path used in the `req_params` object.
SP API Documentation: https://developer-docs.amazon.com/sp-api/docs/data-kiosk-api-v2023-11-15-reference#get-datakiosk2023-11-15documentsdocumentid
* [`lib/resources/versions/data_kiosk/dataKiosk_2023-11-15.js`](diffhunk://#diff-0427c60a56fcd5a4c8049212201a5ba6f7ee254d9ed3ec62e348207a5703cc87L57-R57): Changed the `api_path` from `/dataKiosk/2023-11-15/queries/` to `/dataKiosk/2023-11-15/documents/` to correct the endpoint being accessed.
=> fix(data-kiosk): incorrect url for data kiosk documents

lib/typings/operations/reports.ts
fixing the following typescript error:
Return type of public method from exported class has or is using name 'Report' from external module "F:/.../node_modules/amazon-sp-api/lib/typings/operations/reports" but cannot be named.
=> Fix typescript error

lib/SellingPartner.js
Thank you for incorporating my earlier pull request #148 to add timeout options. We have updated our production code to use the timeout options that the library now supports and have encountered an issue which this new PR should fix:
When timeout options have been specified for an API call, it is still currently possible for the call to take longer or even hang up. This happens when the current access_token is not valid. In this case, the library makes a http request to get a new access_token via the refreshToken call. If this request does not complete the code can hang. This is rare but we have observed it in production code.
This pull request stores the timeout options for the current call in a new SellingPartner object property. The current call timeout options are then used for any …
=> Apply timeout options to access_token refresh call
